### ISSUE TITLE
Items did show in the component tab in the mechbay overwiew, but not in the mechbay itself.

### ISSUE THREAD

**Issue by Tubben** [m22spencer/BattletechPerformanceFix#20] opened 2018-08-13 22:47 UTC
[BattletechPerformanceFix.log](https://github.com/m22spencer/BattletechPerformanceFix/files/2284970/BattletechPerformanceFix.log)
![20180814001807_1](https://user-images.githubusercontent.com/10608926/44062160-8828216c-9f5b-11e8-8984-cfa7161a4238.jpg)
![20180814001739_1](https://user-images.githubusercontent.com/10608926/44062186-9d19271a-9f5b-11e8-8929-f742659068a5.jpg)

**Comment by m22spencer** [comment] 2018-08-14 13:25
I'm not able to reproduce this locally, as the HSK (D) shows up in my mechbay even with the fix.

Can you try running with this build https://github.com/m22spencer/BattletechPerformanceFix/releases/tag/1.0.5.1

Just attach the BattletechPerformanceFix.log file here.

Thanks

**Comment by m22spencer** [comment] 2018-08-19 00:32
resolved in d059b0c

**Closed by m22spencer** 2018-08-19 00:32 UTC
